#!/usr/bin/env python3

import argparse;
import subprocess;
import webbrowser;

videos = {
    "fancy": {
        "title": "FANCY",
        "alias": ["fncy"],
        "url": "https://www.youtube.com/watch?v=kOHB85vDuow"
    },
    "kura kura": {
        "title": "Kura Kura",
        "alias": ["kura"],
        "url": "https://www.youtube.com/watch?v=BSS8Y-0hOlY",
    },
    "better": {
        "title": "Better",
        "alias": [],
        "url": "https://www.youtube.com/watch?v=sLmLwgxnPUE"
    },
    "yes or yes": {
        "title": "Yes or Yes",
        "alias": ["yesoryes","yes"],
        "url": "https://www.youtube.com/watch?v=mAKsZ26SabQ"
    },
    "i cant stop me": {
        "title": "I CAN'T STOP ME",
        "alias": ["cantstop", "stopme"],
        "url": "https://www.youtube.com/watch?v=CM4CkVFmTds"
    },
    "what is love?": {
        "title": "What is Love?",
        "alias": ["what is love", "whatislove", "whatlove"],
        "url": "https://www.youtube.com/watch?v=i0p1bmr0EmE"
    },
    "switch to me": {
        "title": "Switch to me",
        "alias": ["switch", "switchtome"],
        "url": "https://www.youtube.com/watch?v=5UMgw3V-Q5I"
    },
    "more & more": {
        "title": "MORE & MORE",
        "alias": ["more and more", "moremore", "morenmore"],
        "url": "https://www.youtube.com/watch?v=mH0_XpSHkZo"
    },
    "likey": {
        "title": "LIKEY",
        "alias": [],
        "url": "https://www.youtube.com/watch?v=V2hlQkVJZhE",
    },
    "feel special": {
        "title": "Feel Special",
        "alias": ["feelspecial"],
        "url": "https://www.youtube.com/watch?v=3ymwOvzhwHs"
    },
    "tt": {
        "title": "TT",
        "alias": [],
        "url": "https://www.youtube.com/watch?v=ePpPVE-GGJw",
    },
    "cheer up": {
        "title": "CHEER UP",
        "alias": ["cheer", "cheerup"],
        "url": "https://www.youtube.com/watch?v=c7rCyll5AeY",
    },
    "like ooh-aah": {
        "title": "Like OOH-AHH(OOH-AHH하게)",
        "alias": ["likeooh","oohaah","ooh-aah","likeoohaah"],
        "url": "https://www.youtube.com/watch?v=0rtV5esQT6I",
    },
    "knock knock": {
        "title": "Knock Knock",
        "alias": ["knock","knockknock"],
        "url": "https://www.youtube.com/watch?v=8A2t_tAjMz8"
    },
    "i want you back": {
        "title": "I WANT YOU BACK",
        "alias": ["youback", "wantyouback", "wantback", "iwantyouback"],
        "url": "https://www.youtube.com/watch?v=X3H-4crGD6k"
    },
    "heart shaker": {
        "title": "Heart Shaker",
        "alias": ["heartshaker", "shaker"],
        "url": "https://www.youtube.com/watch?v=rRzxEiBLQCA",
    },
    "signal": {
        "title": "Signal",
        "alias": [],
        "url": "https://www.youtube.com/watch?v=VQtonf1fv_s"
    },
    "bdz": {
        "title": "BDZ",
        "alias": [],
        "url": "https://www.youtube.com/watch?v=CMNahhgR_ss"
    },
    "brand new girl": {
        "title": "Brand New Girl",
        "alias": ["newgirl", "brandnewgirl", "brandnew"],
        "url": "https://www.youtube.com/watch?v=r1CMjQ0QJ1E"
    },
    "one more time": {
        "title": "One More Time",
        "alias": ["onemoretime", "onetime"],
        "url": "https://www.youtube.com/watch?v=HuoOEry-Yc4"
    },
    "merry & happy": {
        "title": "Merry & Happy",
        "alias": ["merryandhappy", "merry&happy","merryhappy"],
        "url": "https://www.youtube.com/watch?v=zi_6oaQyckM"
    },
    "candy pop": {
        "title": "Candy Pop",
        "alias": ["candypop"],
        "url": "https://www.youtube.com/watch?v=wQ_POfToaVY"
    },
    "alcohol-free": {
        "title": "Alcohol-Free",
        "alias": ["alcoholfree","alcohol free","alcohol","alcfree"],
        "url": "https://www.youtube.com/watch?v=XA2YEHn-A8Q"
    },
    "breakthrough": {
        "title": "Breakthrough",
        "alias":  ["break"],
        "url": "https://www.youtube.com/watch?v=ZdKYi5ekshM"
    },
    "perfect world": {
        "title": "Perfect World",
        "alias": ["perfect", "perfectworld", "perfworld"],
        "url": "https://www.youtube.com/watch?v=fmOEKOjyDxU"
    },
    "the feels": {
        "title": "The Feels",
        "alias": ["thefeels", "feels"],
        "url": "https://www.youtube.com/watch?v=f5_wn8mexmM"
    }
}

def handle(args):
    if args.list:
        for video in videos.values():            
            print(f"- {video['title']}")

    if args.video:
        play_video(args.video, args.vlc)

def play_video(title: str, vlc):
    title = title.lower()
    url = ""
    if title not in videos.keys():
        for value in videos.values():
            if title in value["alias"]:
                url = value["url"]
        if url == "":
            return
    else:
        url = videos[title]["url"]

    if vlc:
        subprocess.run(["vlc", url])
    else:
        webbrowser.open(url, new=2)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("video", help="Which MV to watch", nargs='?')
    parser.add_argument("--list", help="List available MVs", action="store_true")
    parser.add_argument("--vlc", help="Use VLC", action="store_true")
    handle(parser.parse_args())

if __name__ == "__main__":
    main()